### ISSUE TITLE
Unknown tags

### ISSUE THREAD

**Issue by Creeperface01** [nette-intellij/intellij-latte#113] opened 2020-07-21 08:20 UTC
After updating to the latest version, plugin reports errors almost everywhere.
Even in the simplest cases like this
![image](https://user-images.githubusercontent.com/10363500/88030691-d9742d00-cb3b-11ea-980c-52041bb4b198.png)

Also formatting is broken and the closing tag is generated without indentation
![image](https://user-images.githubusercontent.com/10363500/88030630-c6615d00-cb3b-11ea-8f65-a79200c15b68.png)

Using IntelliJ ultimate 2020.1.3

**Comment by Creeperface01** [comment] 2020-07-21 08:48
However now it seems to be fixed after reinstalling the plugin

**Comment by mesour** [comment] 2020-07-21 11:26
Unknown tags were because you missed notification with reparse files. After you install 1.1.0 you must click to it. Restarting PHPStorm also resolves this issue. But you can use button in notification only without a restart.

Problem with formatting was fixed too? If not, please open new issue with formatting bug only.

**Comment by Creeperface01** [comment] 2020-07-21 11:37
I used that button but it didn't fix it. I also tried restarting IDE even invalidating caches but without success. I'm not using PHPStorm but IntelliJ ultimate so I don't know if that could be a problem. And the formatting was broken because of unknown tags errors.

**Comment by mesour** [comment] 2020-07-21 11:49
@Creeperface01 OK thank you for more information. I will test it in IntelliJ Ultimate. But, in theory, it should have no effect.

And I will test the button in the notification too.

**Comment by kolinger** [comment] 2020-07-21 14:53
I have similar problem. Most projects are fixed with `Reparse files` notification. But with few `Reparse files` didn't help.

I seems like when I work (and edit latte) before `Reparse file` then reparse won't work (reparse will end with success but tags are not fixed). After IDE restart - tags are working and `Reparse file` notification appears again. This is not 100% consistent though. Sometimes (less often) reparse works even after editing latte.

I'm using latest PhpStorm with latest version of this plugin.

**Comment by mesour** [comment] 2020-07-22 06:11
As first is important to understand, how PhpStorm works. And here are no callbacks, that are triggered after all files are indexed. But plugin can register a handler for specific files indexing. Plugin configurations are loaded to RAM if PHPStorm starts and is changed if some .xml configuration file is changed or removed. Here is the case if you already have .latte files open you must reparse it after configuration is loaded (here is no lifecycle, sometimes is loaded .xml configuration before an opened file and sometimes after). In PHPStorm is not possible to reparse files during indexing action. It is, why I used notification. If you click during indexing to reparse, it will show the new notification with information, that you must reparse after indexing.

I think maybe here are possible some improvements, that will show notification less often or better description in notifications. But sometimes it can be shown (especially if you edit or delete `latte-intellij.xml` file). But now it is shown every time. The plugin internally also use .xml configuration loaded to `.idea/intellij-latte/xmlSources`.

Here are two types of notifications. The first type is:

- This type is shown after you install Latte plugin without or you upgrade it to 1.1.0 from lower version (for all projects separately)
- It is because files are copied to .idea folder and here is some difference if it is a new file node or only updates existing

<img width="1040" alt="Snímek obrazovky 2020-07-22 v 6 32 56" src="https://user-images.githubusercontent.com/1161897/88139241-92e00a80-cbef-11ea-9c1e-a6d75a171483.png">

And the second type:

- This type is shown after you start PHPStorm or update/delete some `latte-intellij.xml` in your project
- Or if some package is reloaded in the vendor folder and have `latte-intellij.xml` file

<img width="626" alt="Snímek obrazovky 2020-07-22 v 6 33 00" src="https://user-images.githubusercontent.com/1161897/88139499-1b5eab00-cbf0-11ea-94fb-4b615f1c7a73.png">

-----

I tested it and it is working for me like description bellow (new installation of plugin 1.1.0 in `PhpStorm 2020.1.3` (201.8538.41).

**Comment by mesour** [comment] 2020-07-22 06:15
@kolinger it is hard to reproduce it. The recommended way is editing .latte files after you click to `Reparse files`. Here will be documentation for Nette plugins with this information. But now I'm working on it.

**Comment by Creeperface01** [comment] 2020-07-22 06:30
Not sure if it's helpful or related but it happened even in newly created files for me.

**Comment by mesour** [comment] 2020-07-22 07:06
> Not sure if it's helpful or related but it happened even in newly created files for me.

Can you record this behavior to video upload somewhere and send a link to this issue?

**Comment by kolinger** [comment] 2020-07-22 07:53
My previous description was not accurate - this is not related to editing latte before but waiting/doing other work before. I can reproduce this every time 1. open project 2. work on php files for few minutes 3. open latte 4. click reparse notification - and it never works. IDE restart is required always.

In my case I'm always opening old projects (edited with previous plugin version), not modifing or updating vendor or changing .idea directory.

**Comment by mesour** [comment] 2020-07-22 08:08
@kolinger and which type of notification is showing for you? `first` type or `second` type (described in my post above). If you opening old projects (edited with previous plugin version), `first` and `second` notification must be shown. If you click only to notification with type `second`, it will not fix the problem unknown tags. The best way is to click to notification type `first` as first and after to `second` type.

**Comment by kolinger** [comment] 2020-07-22 08:30
I get only first `new plugin`. I don't get second at all. Once (1 of 10) I did get both and first didn't work and second did but that's very rare to get both.

**Comment by mesour** [comment] 2021-02-12 01:09
It looks like now is everything OK. I can't reproduce the problem with the new plugin version.

I'm closing the issue, if the problem will occur again, let's reopen the issue.

**Closed by mesour** 2021-02-12 01:09 UTC
